# This is a basic workflow to help you get started with Actions.
name: ZAP Scan petstore
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
       main
  pull_request: 
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    # runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    step1:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       name: checkout
       uses: actions/checkout@v3
       # Setup python and Owasp ZAP
    step2:   
       name: setup python
       uses: actions/setup-python@v4
         with:
         python-version:3.10.5 
    step3:    
       name3: Install python dependencies
       run: |
          python -m pip install --upgrade pip
          pip install requests python-owasp-zap-v2.10.0 
    step4:     
       name4: Install OWASP ZAP
       run: |
          mkdir -p ./zap 
          cd ./zap
          wget https://github.com/zaproxy/zaproxy/releases/download/2.10.0/ZAP_2.10.0_Linux.tar.gz
          tar -xzvf ZAP_2.10.0_Linux.tar.gz
          rm ZAP_2.10.0_Linux.tar.gz
          chmod +x start-zap
          chmod +x start-gui-zap
          chmod +x stop zap
    step5:
       name: Run ZAP
       run: ./zap/ZAP_2.10.0/zap.sh -daemon -host 0.0.0.0 -port 8090 
    step6:
       name: Sleep 
       run: sleep 60 
        
        
        
        
        
       
          
          
          
          
          
